[target.aarch64-linux-android]
ar = "aarch64-linux-android-ar.exe"
linker = "aarch64-linux-android23-clang++.cmd"
rustflags = [
    "-C", "link-arg=-DMAGICKCORE_HDRI_ENABLE=1",
    "-C", "link-arg=-DMAGICKCORE_QUANTUM_DEPTH=16"
]

[target.armv7-linux-androideabi]
ar = "arm-linux-androideabi-ar.exe"
linker = "armv7a-linux-androideabi23-clang++.cmd"
rustflags = [
    "-C", "link-arg=-DMAGICKCORE_HDRI_ENABLE=1",
    "-C", "link-arg=-DMAGICKCORE_QUANTUM_DEPTH=16"
]

[env]
MAGICKCORE_HDRI_ENABLE = "1"
MAGICKCORE_QUANTUM_DEPTH = "16"
CFLAGS = "-DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16"
CXXFLAGS = "-DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16"