# Android NDK target configurations
[target.aarch64-linux-android]
ar = "aarch64-linux-android-ar"
linker = "aarch64-linux-android23-clang++"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
    "-C", "target-feature=+neon",
]

[target.armv7-linux-androideabi]
ar = "arm-linux-androideabi-ar"
linker = "armv7a-linux-androideabi23-clang++"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
    "-C", "target-feature=+neon",
]

[target.i686-linux-android]
ar = "i686-linux-android-ar"
linker = "i686-linux-android23-clang++"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
]

[target.x86_64-linux-android]
ar = "x86_64-linux-android-ar"
linker = "x86_64-linux-android23-clang++"
rustflags = [
    "-C", "link-arg=-landroid",
    "-C", "link-arg=-llog",
]