# cargo-ndk configuration for kmagick
# This file helps cargo-ndk automatically configure Android builds

[ndk]
# Android API level to target (23 = Android 6.0, good compatibility)
platform = 23

# Automatically detect NDK from environment variables
auto_detect_ndk = true

[build]
# Default build profiles for different scenarios
[build.debug]
target-dir = "target"

[build.release] 
target-dir = "target"
lto = true
codegen-units = 1

# Target-specific configurations
[target.aarch64-linux-android]
# ARM64 (arm64-v8a) - Modern Android devices
rustflags = [
    "-C", "link-args=-DMAGICKCORE_QUANTUM_DEPTH=16",
    "-C", "link-args=-DMAGICKCORE_HDRI_ENABLE=1"
]

[target.armv7-linux-androideabi]
# ARM (armeabi-v7a) - Older Android devices
rustflags = [
    "-C", "link-args=-DMAGICKCORE_QUANTUM_DEPTH=16", 
    "-C", "link-args=-DMAGICKCORE_HDRI_ENABLE=1"
]

[target.i686-linux-android]
# x86 - Android emulators
rustflags = [
    "-C", "link-args=-DMAGICKCORE_QUANTUM_DEPTH=16",
    "-C", "link-args=-DMAGICKCORE_HDRI_ENABLE=1"
]

[target.x86_64-linux-android]
# x86_64 - Modern Android emulators  
rustflags = [
    "-C", "link-args=-DMAGICKCORE_QUANTUM_DEPTH=16",
    "-C", "link-args=-DMAGICKCORE_HDRI_ENABLE=1"
]